/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccountValidationAssistanceApi,
  AccountsApi,
  AccountsSimpleApi,
  AppRegistrationApi,
  AssetsApi,
  AuthenticationApi,
  BalanceAnalyticsApi,
  BankStatementsApi,
  BusinessesApiApi,
  CashFlowApi,
  CashFlowAnalyticsApi,
  ConnectApi,
  ConsumersApi,
  CustomerAuthorizationDetailsApi,
  CustomersApi,
  InstitutionsApi,
  PayStatementsApi,
  PaymentHistoryApi,
  PaymentsApi,
  PortfoliosApi,
  ReportsApi,
  ThirdPartyAccessApi,
  TransactionsApi,
  TxPushApi,
  VerifyAssetsApi,
  VerifyIncomeAndEmploymentApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { MastercardCustom } from "./client-custom";

export class Mastercard extends MastercardCustom {
  readonly accountValidationAssistance: AccountValidationAssistanceApi;
  readonly accounts: AccountsApi;
  readonly accountsSimple: AccountsSimpleApi;
  readonly appRegistration: AppRegistrationApi;
  readonly assets: AssetsApi;
  readonly authentication: AuthenticationApi;
  readonly balanceAnalytics: BalanceAnalyticsApi;
  readonly bankStatements: BankStatementsApi;
  readonly businessesApi: BusinessesApiApi;
  readonly cashFlow: CashFlowApi;
  readonly cashFlowAnalytics: CashFlowAnalyticsApi;
  readonly connect: ConnectApi;
  readonly consumers: ConsumersApi;
  readonly customerAuthorizationDetails: CustomerAuthorizationDetailsApi;
  readonly customers: CustomersApi;
  readonly institutions: InstitutionsApi;
  readonly payStatements: PayStatementsApi;
  readonly paymentHistory: PaymentHistoryApi;
  readonly payments: PaymentsApi;
  readonly portfolios: PortfoliosApi;
  readonly reports: ReportsApi;
  readonly thirdPartyAccess: ThirdPartyAccessApi;
  readonly transactions: TransactionsApi;
  readonly txPush: TxPushApi;
  readonly verifyAssets: VerifyAssetsApi;
  readonly verifyIncomeAndEmployment: VerifyIncomeAndEmploymentApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.accountValidationAssistance = new AccountValidationAssistanceApi(configuration);
    this.accounts = new AccountsApi(configuration);
    this.accountsSimple = new AccountsSimpleApi(configuration);
    this.appRegistration = new AppRegistrationApi(configuration);
    this.assets = new AssetsApi(configuration);
    this.authentication = new AuthenticationApi(configuration);
    this.balanceAnalytics = new BalanceAnalyticsApi(configuration);
    this.bankStatements = new BankStatementsApi(configuration);
    this.businessesApi = new BusinessesApiApi(configuration);
    this.cashFlow = new CashFlowApi(configuration);
    this.cashFlowAnalytics = new CashFlowAnalyticsApi(configuration);
    this.connect = new ConnectApi(configuration);
    this.consumers = new ConsumersApi(configuration);
    this.customerAuthorizationDetails = new CustomerAuthorizationDetailsApi(configuration);
    this.customers = new CustomersApi(configuration);
    this.institutions = new InstitutionsApi(configuration);
    this.payStatements = new PayStatementsApi(configuration);
    this.paymentHistory = new PaymentHistoryApi(configuration);
    this.payments = new PaymentsApi(configuration);
    this.portfolios = new PortfoliosApi(configuration);
    this.reports = new ReportsApi(configuration);
    this.thirdPartyAccess = new ThirdPartyAccessApi(configuration);
    this.transactions = new TransactionsApi(configuration);
    this.txPush = new TxPushApi(configuration);
    this.verifyAssets = new VerifyAssetsApi(configuration);
    this.verifyIncomeAndEmployment = new VerifyIncomeAndEmploymentApi(configuration);
  }

}
