/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountDetails } from './account-details';
import { AccountDetailsTxBasedAllOf } from './account-details-tx-based-all-of';

/**
 * @type AccountDetailsTxBased
 * @export
 */
export type AccountDetailsTxBased = AccountDetails & AccountDetailsTxBasedAllOf;


