/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AFBusinessAddress } from './afbusiness-address';

/**
 * 
 * @export
 * @interface AFBusiness
 */
export interface AFBusiness {
    /**
     * The name of a business
     * @type {string}
     * @memberof AFBusiness
     */
    'name': string;
    /**
     * 
     * @type {AFBusinessAddress}
     * @memberof AFBusiness
     */
    'address': AFBusinessAddress;
}

