/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomerAnalytics } from './customer-analytics';
import { ReportInstitution } from './report-institution';

/**
 * 
 * @export
 * @interface AFCashFlowAnalyticsReportAllOf
 */
export interface AFCashFlowAnalyticsReportAllOf {
    /**
     * The `postedDate` of the earliest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'startDate'?: number;
    /**
     * The `postedDate` of the latest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'endDate'?: number;
    /**
     * Number of days covered by the report
     * @type {number}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'days'?: number;
    /**
     * \"true\" if the report covers more than 365 days
     * @type {boolean}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'seasoned'?: boolean;
    /**
     * A list of institution records, including information about the individual accounts used in this report
     * @type {Array<ReportInstitution>}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'institutions'?: Array<ReportInstitution>;
    /**
     * 
     * @type {CustomerAnalytics}
     * @memberof AFCashFlowAnalyticsReportAllOf
     */
    'customerAnalytics'?: CustomerAnalytics;
}

