/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AFCashFlowAnalyticsReportAllOf } from './afcash-flow-analytics-report-all-of';
import { AnalyticsReportAck } from './analytics-report-ack';
import { AnalyticsReportConstraintsOut } from './analytics-report-constraints-out';
import { BusinessDetails } from './business-details';
import { CustomerAnalytics } from './customer-analytics';
import { ErrorMessage } from './error-message';
import { ReportInstitution } from './report-institution';

/**
 * @type AFCashFlowAnalyticsReport
 * A Cash Flow Analytics Report
 * @export
 */
export type AFCashFlowAnalyticsReport = AFCashFlowAnalyticsReportAllOf & AnalyticsReportAck;


