/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountAnalytics } from './account-analytics';
import { AccountDetails } from './account-details';
import { ReportTransaction } from './report-transaction';

/**
 * 
 * @export
 * @interface AnalyticsReportsAccount
 */
export interface AnalyticsReportsAccount {
    /**
     * The ID of the account
     * @type {number}
     * @memberof AnalyticsReportsAccount
     */
    'id': number;
    /**
     * The name(s) of the account owner(s), retrieved from the institution.
     * @type {string}
     * @memberof AnalyticsReportsAccount
     */
    'ownerName'?: string;
    /**
     * The mailing address of the account owner, retrieved from the institution.
     * @type {string}
     * @memberof AnalyticsReportsAccount
     */
    'ownerAddress'?: string;
    /**
     * The account name from the institution
     * @type {string}
     * @memberof AnalyticsReportsAccount
     */
    'name': string;
    /**
     * The account number from the institution (obfuscated)
     * @type {string}
     * @memberof AnalyticsReportsAccount
     */
    'number': string;
    /**
     * One of the values from account types
     * @type {string}
     * @memberof AnalyticsReportsAccount
     */
    'type': string;
    /**
     * The status of the most recent aggregation attempt
     * @type {number}
     * @memberof AnalyticsReportsAccount
     */
    'aggregationStatusCode'?: number;
    /**
     * The cleared balance of the account as-of `balanceDate`
     * @type {number}
     * @memberof AnalyticsReportsAccount
     */
    'currentBalance'?: number;
    /**
     * Available balance
     * @type {number}
     * @memberof AnalyticsReportsAccount
     */
    'availableBalance'?: number;
    /**
     * A timestamp showing when the `balance` was captured
     * @type {number}
     * @memberof AnalyticsReportsAccount
     */
    'balanceDate'?: number;
    /**
     * a list of transaction records
     * @type {Array<ReportTransaction>}
     * @memberof AnalyticsReportsAccount
     */
    'transactions': Array<ReportTransaction>;
    /**
     * 
     * @type {AccountDetails}
     * @memberof AnalyticsReportsAccount
     */
    'details'?: AccountDetails;
    /**
     * 
     * @type {AccountAnalytics}
     * @memberof AnalyticsReportsAccount
     */
    'accountAnalytics'?: AccountAnalytics;
}

