/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Request parameters from the partner to control the customer accounts included in the report, and the length of time to report on.
 * @export
 * @interface BalanceAndCashFlowAnalyticsReportConstraints
 */
export interface BalanceAndCashFlowAnalyticsReportConstraints {
    /**
     * The list of account IDs to include in the report. If omitted, all accounts on record for the customer will be used.
     * @type {Array<number>}
     * @memberof BalanceAndCashFlowAnalyticsReportConstraints
     */
    'accountIds'?: Array<number>;
    /**
     * Number of days to search for transactions. Must be one of 30, 90, 180, 270, 365, or 730. If omitted, defaults to 2 years from current time at which the request was received (730 days).
     * @type {number}
     * @memberof BalanceAndCashFlowAnalyticsReportConstraints
     */
    'lengthOfReport'?: number;
}

