/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BaseReportAck } from './base-report-ack';
import { BaseReportAckWithPortfolioIdAllOf } from './base-report-ack-with-portfolio-id-all-of';
import { ErrorMessage } from './error-message';

/**
 * @type BaseReportAckWithPortfolioId
 * Properties shared by all generated reports having a portfolio ID
 * @export
 */
export type BaseReportAckWithPortfolioId = BaseReportAck & BaseReportAckWithPortfolioIdAllOf;


