/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A birth date
 * @export
 * @interface Birthday
 */
export interface Birthday {
    /**
     * The birthday 4-digit year
     * @type {number}
     * @memberof Birthday
     */
    'year'?: number;
    /**
     * The birthday 2-digit month (1 is January)
     * @type {number}
     * @memberof Birthday
     */
    'month'?: number;
    /**
     * The birthday 2-digit day-of-month
     * @type {number}
     * @memberof Birthday
     */
    'dayOfMonth'?: number;
}

