/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Branding } from './branding';

/**
 * 
 * @export
 * @interface BrandingWrapper
 */
export interface BrandingWrapper {
    /**
     * 
     * @type {Branding}
     * @memberof BrandingWrapper
     */
    'branding': Branding;
}

