/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashFlowInflowAttributes } from './cash-flow-inflow-attributes';
import { CashFlowNegativeTriggers } from './cash-flow-negative-triggers';
import { CashFlowOutflowAttributes } from './cash-flow-outflow-attributes';
import { CashFlowTransactionAnalyticsAttributes } from './cash-flow-transaction-analytics-attributes';
import { ObbDateRangeAndAmount } from './obb-date-range-and-amount';

/**
 * Cash flow analytics metrics and calculations
 * @export
 * @interface CashFlowAnalyticsMetrics
 */
export interface CashFlowAnalyticsMetrics {
    /**
     * 
     * @type {CashFlowInflowAttributes}
     * @memberof CashFlowAnalyticsMetrics
     */
    'inflow'?: CashFlowInflowAttributes;
    /**
     * 
     * @type {CashFlowNegativeTriggers}
     * @memberof CashFlowAnalyticsMetrics
     */
    'negativeTriggers'?: CashFlowNegativeTriggers;
    /**
     * 
     * @type {CashFlowOutflowAttributes}
     * @memberof CashFlowAnalyticsMetrics
     */
    'outflow'?: CashFlowOutflowAttributes;
    /**
     * Sum of all transactions categorized as revenue, split by months
     * @type {Array<ObbDateRangeAndAmount>}
     * @memberof CashFlowAnalyticsMetrics
     */
    'revenueByMonthForTheReportTimePeriod'?: Array<ObbDateRangeAndAmount>;
    /**
     * Sum of all transactions categorized as revenue
     * @type {number}
     * @memberof CashFlowAnalyticsMetrics
     */
    'revenueForTheReportTimePeriod'?: number;
    /**
     * 
     * @type {CashFlowTransactionAnalyticsAttributes}
     * @memberof CashFlowAnalyticsMetrics
     */
    'transactionAnalytics'?: CashFlowTransactionAnalyticsAttributes;
}

