/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashFlowInsufficientFundsFees } from './cash-flow-insufficient-funds-fees';

/**
 * Transactions that may be warning signs of bad creditworthiness
 * @export
 * @interface CashFlowNegativeTriggers
 */
export interface CashFlowNegativeTriggers {
    /**
     * 
     * @type {CashFlowInsufficientFundsFees}
     * @memberof CashFlowNegativeTriggers
     */
    'insufficientFundFees'?: CashFlowInsufficientFundsFees;
}

