/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashFlowMonthlyCashFlowCredits } from './cash-flow-monthly-cash-flow-credits';

/**
 * 
 * @export
 * @interface CashFlowCashFlowCredit
 */
export interface CashFlowCashFlowCredit {
    /**
     * List of attributes for each month
     * @type {Array<CashFlowMonthlyCashFlowCredits>}
     * @memberof CashFlowCashFlowCredit
     */
    'monthlyCashFlowCredits': Array<CashFlowMonthlyCashFlowCredits>;
    /**
     * Sum of all credit transactions for each month by account
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'twelveMonthCreditTotal'?: number;
    /**
     * Sum of all monthly credit transactions without transfers for the account
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'twelveMonthCreditTotalLessTransfers'?: number;
    /**
     * Sum of six month credit transactions
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'sixMonthCreditTotal'?: number;
    /**
     * Sum of six month credit transactions without transfers
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'sixMonthCreditTotalLessTransfers'?: number;
    /**
     * Sum of two month credit transactions
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'twoMonthCreditTotal'?: number;
    /**
     * Sum of two month credit transactions without transfers
     * @type {number}
     * @memberof CashFlowCashFlowCredit
     */
    'twoMonthCreditTotalLessTransfers'?: number;
}

