/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CashFlowMonthlyCashFlowBalanceSummaries
 */
export interface CashFlowMonthlyCashFlowBalanceSummaries {
    /**
     * One instance for each complete calendar month in the report
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'month': number;
    /**
     * Min Daily Balance for each month for all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'minDailyBalance': number;
    /**
     * Max Daily Balance for each month for all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'maxDailyBalance': number;
    /**
     * Average Daily Balance for each month for all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'averageDailyBalance': number;
    /**
     * Standard Deviation of Daily Balance for each month for all accounts
     * @type {string}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'standardDeviationOfDailyBalance'?: string;
    /**
     * Number of Days Negative Balance for each month for all accounts
     * @type {string}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'numberOfDaysNegativeBalance': string;
    /**
     * Number of Days Positive Balance for each month for all accounts
     * @type {string}
     * @memberof CashFlowMonthlyCashFlowBalanceSummaries
     */
    'numberOfDaysPositiveBalance': string;
}

