/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashFlowPossibleLoanDepositsAccount } from './cash-flow-possible-loan-deposits-account';

/**
 * 
 * @export
 * @interface CashFlowPossibleLoanDepositsInstitutions
 */
export interface CashFlowPossibleLoanDepositsInstitutions {
    /**
     * Finicity institution ID
     * @type {string}
     * @memberof CashFlowPossibleLoanDepositsInstitutions
     */
    'id': string;
    /**
     * Finicity institution name
     * @type {string}
     * @memberof CashFlowPossibleLoanDepositsInstitutions
     */
    'name': string;
    /**
     * The URL of the Financial Institution
     * @type {string}
     * @memberof CashFlowPossibleLoanDepositsInstitutions
     */
    'urlHomeApp': string;
    /**
     * A list of account records
     * @type {Array<CashFlowPossibleLoanDepositsAccount>}
     * @memberof CashFlowPossibleLoanDepositsInstitutions
     */
    'accounts': Array<CashFlowPossibleLoanDepositsAccount>;
}

