/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CashFlowActivityDepositsCredits } from './cash-flow-activity-deposits-credits';
import { CashFlowActivityWithdrawalsDebits } from './cash-flow-activity-withdrawals-debits';
import { CashFlowNumWeeksZeros } from './cash-flow-num-weeks-zeros';
import { CashFlowTransactionAnalyticsAttributesLastTransactionDateInner } from './cash-flow-transaction-analytics-attributes-last-transaction-date-inner';
import { ObbDateRangeAndAmount } from './obb-date-range-and-amount';

/**
 * Transaction Analytics Attributes
 * @export
 * @interface CashFlowTransactionAnalyticsAttributes
 */
export interface CashFlowTransactionAnalyticsAttributes {
    /**
     * List of all deposit transactions posted to the account during the report period
     * @type {Array<CashFlowActivityDepositsCredits>}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'activityDepositsCreditsForTheReportTimePeriod': Array<CashFlowActivityDepositsCredits>;
    /**
     * List of all withdrawal transactions posted to the account during the report period
     * @type {Array<CashFlowActivityWithdrawalsDebits>}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'activityWithdrawalsDebitsForTheReportTimePeriod': Array<CashFlowActivityWithdrawalsDebits>;
    /**
     * Average value of transactions during periods in the report. Values may be positive or negative
     * @type {Array<ObbDateRangeAndAmount>}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'averageTransactionValueByMonthForTheReportTimePeriod': Array<ObbDateRangeAndAmount>;
    /**
     * 
     * @type {CashFlowNumWeeksZeros}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'historicWeeksWithZeroTransactions'?: CashFlowNumWeeksZeros;
    /**
     * Latest posted transaction(s) to the account. May be more than one if they share the same timestamp
     * @type {Array<CashFlowTransactionAnalyticsAttributesLastTransactionDateInner>}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'lastTransactionDate'?: Array<CashFlowTransactionAnalyticsAttributesLastTransactionDateInner>;
    /**
     * Net cash flow for each month during the report period
     * @type {Array<ObbDateRangeAndAmount>}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'netCashFlowByMonthForTheReportTimePeriod'?: Array<ObbDateRangeAndAmount>;
    /**
     * Net cash flow during the report period (may be positive or negative)
     * @type {number}
     * @memberof CashFlowTransactionAnalyticsAttributes
     */
    'netCashFlowForTheReportTimePeriod'?: number;
}

