/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CashFlowMonthlyCashFlowCharacteristicsSummaries
 */
export interface CashFlowMonthlyCashFlowCharacteristicsSummaries {
    /**
     * One instance for each complete calendar month in the report
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowCharacteristicsSummaries
     */
    'month': number;
    /**
     * Total Credits - Total Debits by month across all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowCharacteristicsSummaries
     */
    'totalCreditsLessTotalDebits': number;
    /**
     * Total Credits - Total Debits by month (Without Transfers) across all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowCharacteristicsSummaries
     */
    'totalCreditsLessTotalDebitsLessTransfers': number;
    /**
     * Average transaction amount across all accounts
     * @type {number}
     * @memberof CashFlowMonthlyCashFlowCharacteristicsSummaries
     */
    'averageTransactionAmount': number;
}

