/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
 */
export interface CashFlowTransactionAnalyticsAttributesLastTransactionDateInner {
    /**
     * Date the deposit transaction was posted
     * @type {string}
     * @memberof CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
     */
    'date': string;
    /**
     * Amount of transaction if deposit, otherwise null
     * @type {number}
     * @memberof CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
     */
    'depositsCredits'?: number;
    /**
     * Amount of transaction if withdrawal, otherwise null
     * @type {number}
     * @memberof CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
     */
    'withdrawalsDebits'?: number;
    /**
     * Amount of transaction if zero, otherwise null
     * @type {number}
     * @memberof CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
     */
    'zeroAmountTransaction'?: number;
    /**
     * Description of transaction
     * @type {string}
     * @memberof CashFlowTransactionAnalyticsAttributesLastTransactionDateInner
     */
    'transactionDescription'?: string;
}

