/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ChildInstitution
 */
export interface ChildInstitution {
    /**
     * The RSSD ID is a unique identifier assigned to financial institutions by the Federal Reserve. While the length of the RSSD ID varies by institution, it cannot exceed 10 numerical digits.
     * @type {number}
     * @memberof ChildInstitution
     */
    'rssd': number;
    /**
     * The RSSD ID is a unique identifier assigned to financial institutions by the Federal Reserve. While the length of the RSSD ID varies by institution, it cannot exceed 10 numerical digits.
     * @type {number}
     * @memberof ChildInstitution
     */
    'parentRSSD': number;
    /**
     * The name of the institution
     * @type {string}
     * @memberof ChildInstitution
     */
    'name': string;
    /**
     * The ID of a financial institution, represented as a number
     * @type {number}
     * @memberof ChildInstitution
     */
    'institutionId': number;
}

