/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomerWithAppDataAllOf
 */
export interface CustomerWithAppDataAllOf {
    /**
     * `applicationId` value returned from the Get App Registration Status API and the partner assign the customers to. This cannot be changed once set. Only applicable in cases of partners with multiple registered applications. If the partner only has one app, this can usually be omitted. This field is populated after the app is in a status approved.
     * @type {string}
     * @memberof CustomerWithAppDataAllOf
     */
    'applicationId'?: string;
    /**
     * The name of the application assigned to the customer
     * @type {string}
     * @memberof CustomerWithAppDataAllOf
     */
    'applicationName'?: string;
}

