/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomerAccountMultipleStatement } from './customer-account-multiple-statement';

/**
 * A list of customer account statements
 * @export
 * @interface CustomerAccountMultipleStatements
 */
export interface CustomerAccountMultipleStatements {
    /**
     * List of customer account statements
     * @type {Array<CustomerAccountMultipleStatement>}
     * @memberof CustomerAccountMultipleStatements
     */
    'statements': Array<CustomerAccountMultipleStatement>;
}

