/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomerAuthorizationDetails
 */
export interface CustomerAuthorizationDetails {
    /**
     * Institution login id of the customer.
     * @type {number}
     * @memberof CustomerAuthorizationDetails
     */
    'institutionLoginId': number;
    /**
     * Authorization start date and time in ISO 8601 format.
     * @type {string}
     * @memberof CustomerAuthorizationDetails
     */
    'authorizationStartDate': string;
    /**
     * Authorization end date and time in ISO 8601 format.
     * @type {string}
     * @memberof CustomerAuthorizationDetails
     */
    'authorizationEndDate': string;
}

