/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DirectDeposits
 */
export interface DirectDeposits {
    /**
     * Bank account type:  * `Checking`  * `Savings`  * `Loan`: Loan account employee choose to direct a portion of their net pay to help pay off a loan 
     * @type {string}
     * @memberof DirectDeposits
     */
    'accountTypeCode'?: string;
    /**
     * Direct deposit amount
     * @type {number}
     * @memberof DirectDeposits
     */
    'amount'?: number;
    /**
     * Last four digits of the deposit account number
     * @type {string}
     * @memberof DirectDeposits
     */
    'accountLastFour'?: string;
    /**
     * Routing number for the deposit account
     * @type {string}
     * @memberof DirectDeposits
     */
    'routingNumber'?: string;
}

