/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Deductions } from './deductions';
import { DirectDeposits } from './direct-deposits';
import { Earnings } from './earnings';
import { MainPayStatementFields } from './main-pay-statement-fields';

/**
 * 
 * @export
 * @interface DirectPayStatements
 */
export interface DirectPayStatements {
    /**
     * An ID for the income and employment details for the given pay period
     * @type {string}
     * @memberof DirectPayStatements
     */
    'payrollPayHistoryId': string;
    /**
     * Most recent available pay check
     * @type {boolean}
     * @memberof DirectPayStatements
     */
    'lastPayPeriodIndicator': boolean;
    /**
     * 
     * @type {MainPayStatementFields}
     * @memberof DirectPayStatements
     */
    'mainPayStatementFields': MainPayStatementFields;
    /**
     * Categorization of pay, for the pay period
     * @type {Array<Earnings>}
     * @memberof DirectPayStatements
     */
    'earnings': Array<Earnings>;
    /**
     * Deductions from the pay check
     * @type {Array<Deductions>}
     * @memberof DirectPayStatements
     */
    'deductions'?: Array<Deductions>;
    /**
     * Direct deposit information for the paycheck
     * @type {Array<DirectDeposits>}
     * @memberof DirectPayStatements
     */
    'directDeposits'?: Array<DirectDeposits>;
}

