/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DirectDeposit
 */
export interface DirectDeposit {
    /**
     * The amount of the deposit
     * @type {number}
     * @memberof DirectDeposit
     */
    'amountCurrent'?: number;
    /**
     * The last four numbers of the account the deposit went into
     * @type {string}
     * @memberof DirectDeposit
     */
    'accountLastFour'?: string;
}

