/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Earnings
 */
export interface Earnings {
    /**
     * Where available, the employer description of earnings on the paycheck
     * @type {string}
     * @memberof Earnings
     */
    'name'?: string;
    /**
     * Categorization of the earnings:  * `base`  * `bonus`  * `overtime`  * `commission`  * `tips`  * `other` 
     * @type {string}
     * @memberof Earnings
     */
    'type': string;
    /**
     * Rate of pay
     * @type {number}
     * @memberof Earnings
     */
    'rate'?: number;
    /**
     * Earnings amount for each earning type
     * @type {number}
     * @memberof Earnings
     */
    'amount': number;
    /**
     * Earnings YTD amount if available
     * @type {number}
     * @memberof Earnings
     */
    'amountYTD'?: number;
}

