/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Institution } from './institution';

/**
 * A list of financial institutions from the Get Institutions API
 * @export
 * @interface Institutions
 */
export interface Institutions {
    /**
     * The total number of results matching search criteria
     * @type {number}
     * @memberof Institutions
     */
    'found': number;
    /**
     * The number of results returned
     * @type {number}
     * @memberof Institutions
     */
    'displaying': number;
    /**
     * If the value of `moreAvailable` is \"true\", you can retrieve the next page of results by increasing the value of the start parameter in your next request:\"...&start=6&limit=5\"
     * @type {boolean}
     * @memberof Institutions
     */
    'moreAvailable': boolean;
    /**
     * A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof Institutions
     */
    'createdDate': number;
    /**
     * A list of institutions
     * @type {Array<Institution>}
     * @memberof Institutions
     */
    'institutions': Array<Institution>;
}

