/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InsufficientFundsTransaction
 */
export interface InsufficientFundsTransaction {
    /**
     * Description of the transaction
     * @type {string}
     * @memberof InsufficientFundsTransaction
     */
    'description'?: string;
    /**
     * Amount of the NSF transaction
     * @type {number}
     * @memberof InsufficientFundsTransaction
     */
    'amount': number;
    /**
     * Transaction memo
     * @type {string}
     * @memberof InsufficientFundsTransaction
     */
    'memo'?: string;
    /**
     * Posted date of the NSF transaction
     * @type {string}
     * @memberof InsufficientFundsTransaction
     */
    'postedDate': string;
    /**
     * Finicity transaction ID
     * @type {number}
     * @memberof InsufficientFundsTransaction
     */
    'transactionId': number;
}

