/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LoanPaymentDetailsGroup } from './loan-payment-details-group';
import { LoanPaymentDetailsLoan } from './loan-payment-details-loan';

/**
 * 
 * @export
 * @interface LoanPaymentDetailsAccount
 */
export interface LoanPaymentDetailsAccount {
    /**
     * An account ID
     * @type {string}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountId': string;
    /**
     * Institution\'s ID of the Student Loan Account
     * @type {string}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountNumber': string;
    /**
     * The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number.
     * @type {string}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountPaymentNumber': string;
    /**
     * The payment address to which send manual payments should be sent
     * @type {string}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountPaymentAddress': string;
    /**
     * The payoff amount for the account
     * @type {number}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountFuturePayoffAmount'?: number;
    /**
     * The date to which the \"Future Payoff Amount\" applies
     * @type {string}
     * @memberof LoanPaymentDetailsAccount
     */
    'accountFuturePayoffDate'?: string;
    /**
     * Group details
     * @type {Array<LoanPaymentDetailsGroup>}
     * @memberof LoanPaymentDetailsAccount
     */
    'groupDetail'?: Array<LoanPaymentDetailsGroup>;
    /**
     * Loan details
     * @type {Array<LoanPaymentDetailsLoan>}
     * @memberof LoanPaymentDetailsAccount
     */
    'loanDetail'?: Array<LoanPaymentDetailsLoan>;
}

