/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LoanPaymentDetailsLoan } from './loan-payment-details-loan';

/**
 * Group details
 * @export
 * @interface LoanPaymentDetailsGroup
 */
export interface LoanPaymentDetailsGroup {
    /**
     * An account ID
     * @type {string}
     * @memberof LoanPaymentDetailsGroup
     */
    'accountId': string;
    /**
     * Institution\'s ID of the Student Loan Group
     * @type {string}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupNumber': string;
    /**
     * The payment number given by the institution. This number is typically for manual payments. This is not an ACH payment number.
     * @type {string}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupPaymentNumber': string;
    /**
     * The payment address to which send manual payments should be sent
     * @type {string}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupPaymentAddress': string;
    /**
     * The payoff amount for the group
     * @type {number}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupFuturePayoffAmount'?: number;
    /**
     * The date to which the \"Future Payoff Amount\" applies
     * @type {string}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupFuturePayoffDate'?: string;
    /**
     * 
     * @type {Array<LoanPaymentDetailsLoan>}
     * @memberof LoanPaymentDetailsGroup
     */
    'groupLoanDetail': Array<LoanPaymentDetailsLoan>;
}

