/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A list of amounts
 * @export
 * @interface MicroDepositVerification
 */
export interface MicroDepositVerification {
    /**
     * The list of amounts to be verified
     * @type {Array<number>}
     * @memberof MicroDepositVerification
     */
    'amounts': Array<number>;
}

