/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Current estimated monthly pay for the employment.  This is a mandatory field only for VOIE-payroll report type.
 * @export
 * @interface MonthlyIncome
 */
export interface MonthlyIncome {
    /**
     * Mastercard Open Banking estimated monthly base pay amount for the employment
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyBasePay'?: number;
    /**
     * Mastercard Open Banking estimated monthly overtime pay amount for the employment
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyOvertimePay'?: number;
    /**
     * Mastercard Open Banking estimated monthly bonus pay amount for the employment
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyBonusPay'?: number;
    /**
     * Mastercard Open Banking estimated monthly other pay amount for the employment
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyOtherPay'?: number;
    /**
     * Sum of all Mastercard Open Banking estimated monthly pay amounts
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyTotalPay': number;
    /**
     * Mastercard Open Banking estimated monthly commission pay amount for the employment
     * @type {number}
     * @memberof MonthlyIncome
     */
    'estimatedMonthlyCommissionPay'?: number;
}

