/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface NetMonthly
 */
export interface NetMonthly {
    /**
     * Timestamp for the first day of this month
     * @type {number}
     * @memberof NetMonthly
     */
    'month': number;
    /**
     * Total income during the given month, across all income streams
     * @type {number}
     * @memberof NetMonthly
     */
    'net': number;
}

