/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceAnalyticsAccountResult } from './balance-analytics-account-result';
import { BalanceAnalyticsBusinessSummary } from './balance-analytics-business-summary';
import { BalanceAnalyticsReport } from './balance-analytics-report';
import { CashFlowAnalyticsReport } from './cash-flow-analytics-report';
import { ObbReportHeader } from './obb-report-header';
import { PaymentHistoryAnalytics } from './payment-history-analytics';
import { PaymentHistoryReport } from './payment-history-report';

/**
 * @type ObbAnalyticsReport
 * Cash Flow Analytics, Balance Analytics, and Payment History report data as JSON
 * @export
 */
export type ObbAnalyticsReport = BalanceAnalyticsReport & CashFlowAnalyticsReport & PaymentHistoryReport;


