/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ObbAverageWeeklyBalance
 */
export interface ObbAverageWeeklyBalance {
    /**
     * Average daily ending balance during the week
     * @type {number}
     * @memberof ObbAverageWeeklyBalance
     */
    'amount': number;
    /**
     * Begin date of the week
     * @type {string}
     * @memberof ObbAverageWeeklyBalance
     */
    'fromDate': string;
    /**
     * End date of the week
     * @type {string}
     * @memberof ObbAverageWeeklyBalance
     */
    'toDate': string;
    /**
     * Week number, where the first week of each year begins on January 1st and ends on January 7th. May be in the range [1, 53]
     * @type {number}
     * @memberof ObbAverageWeeklyBalance
     */
    'week': number;
}

