/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Availability of historical data at the time the report was requested
 * @export
 * @interface ObbDataAvailability
 */
export interface ObbDataAvailability {
    /**
     * Begin date for data availability
     * @type {string}
     * @memberof ObbDataAvailability
     */
    'historicAvailabilityBeginDate'?: string;
    /**
     * End date for data availability
     * @type {string}
     * @memberof ObbDataAvailability
     */
    'historicAvailabilityEndDate'?: string;
    /**
     * Days for which transaction details are available
     * @type {number}
     * @memberof ObbDataAvailability
     */
    'historicAvailableDays': number;
    /**
     * Description of historic data availability
     * @type {string}
     * @memberof ObbDataAvailability
     */
    'historicDataAvailability': string;
}

