/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ObbAccountOwner } from './obb-account-owner';
import { ObbInstitution } from './obb-institution';

/**
 * Details of the account and financial institution
 * @export
 * @interface ObbAccountDetails
 */
export interface ObbAccountDetails {
    /**
     * The account number from a financial institution in truncated format
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'accountNumberDisplay'?: string;
    /**
     * 
     * @type {ObbAccountOwner}
     * @memberof ObbAccountDetails
     */
    'accountOwner': ObbAccountOwner;
    /**
     * A timestamp showing the last aggregation attempt. This will not be present until you have run your first aggregation for the account.
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'aggregationAttemptDate'?: string;
    /**
     * The status of the most recent aggregation attempt. This will not be present until you have run your first aggregation for the account
     * @type {number}
     * @memberof ObbAccountDetails
     */
    'aggregationStatusCode'?: number;
    /**
     * A timestamp showing the last successful aggregation of the account. This will not be present until you have run your first aggregation for the account.
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'aggregationSuccessDate'?: string;
    /**
     * The currency of the account
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'currency'?: string;
    /**
     * Current reported balance of the account
     * @type {number}
     * @memberof ObbAccountDetails
     */
    'currentBalance'?: number;
    /**
     * An account ID represented as a number
     * @type {number}
     * @memberof ObbAccountDetails
     */
    'id': number;
    /**
     * 
     * @type {ObbInstitution}
     * @memberof ObbAccountDetails
     */
    'institution': ObbInstitution;
    /**
     * An institution login ID (from the account record), represented as a number
     * @type {number}
     * @memberof ObbAccountDetails
     */
    'institutionLoginId'?: number;
    /**
     * The account name from the institution
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'name'?: string;
    /**
     * The last 4 digits of the ACH account number
     * @type {number}
     * @memberof ObbAccountDetails
     */
    'realAccountNumberLast4'?: number;
    /**
     * pending during account discovery, always active following successful account activation
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'status'?: string;
    /**
     * Account type, e.g. checking/saving
     * @type {string}
     * @memberof ObbAccountDetails
     */
    'type'?: string;
}

