/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VOIEPayStatement } from './voiepay-statement';

/**
 * 
 * @export
 * @interface PayStatementReportAllOf
 */
export interface PayStatementReportAllOf {
    /**
     * The `postedDate` of the earliest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof PayStatementReportAllOf
     */
    'startDate'?: number;
    /**
     * The `postedDate` of the latest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof PayStatementReportAllOf
     */
    'endDate'?: number;
    /**
     * A report style. Possible values are directAPIPayroll, credentialedPayroll, paystatement, voieWithInterview, voieWithStatement, voieWithReport
     * @type {string}
     * @memberof PayStatementReportAllOf
     */
    'reportStyle'?: string;
    /**
     * Total number of billable pay statements included in the report
     * @type {number}
     * @memberof PayStatementReportAllOf
     */
    'numberOfBillableAssets'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof PayStatementReportAllOf
     */
    'assetIds'?: Array<string>;
    /**
     * Extracted pay statement details
     * @type {Array<VOIEPayStatement>}
     * @memberof PayStatementReportAllOf
     */
    'payStatements'?: Array<VOIEPayStatement>;
}

