/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Customer-level summary of transactions in a month
 * @export
 * @interface PaymentHistoryCustomerMonthlySummary
 */
export interface PaymentHistoryCustomerMonthlySummary {
    /**
     * Date of the month
     * @type {string}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'month': string;
    /**
     * Average balance for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'averageBalance': number;
    /**
     * Closing balance for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'closingBalance': number;
    /**
     * Opening balance for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'openingBalance': number;
    /**
     * Total of deposit transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'totalDeposits': number;
    /**
     * Total of withdrawal transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'totalWithdrawals': number;
    /**
     * Total of NSF transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'nonSufficientFunds': number;
    /**
     * Total of insurance payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'insurancePayments': number;
    /**
     * Total of tax payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'taxPayments': number;
    /**
     * Total of recurring expense payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'recurringExpensePayments': number;
    /**
     * Total of missed recurring expense payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'missedRecurringExpensePayments': number;
    /**
     * Total of recurring loan payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'recurringLoanPayments': number;
    /**
     * Total of missed recurring loan payment transactions for the month
     * @type {number}
     * @memberof PaymentHistoryCustomerMonthlySummary
     */
    'missedRecurringLoanPayments': number;
}

