/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollEmployerAddress } from './payroll-employer-address';

/**
 * 
 * @export
 * @interface PayrollEmploymentRecord
 */
export interface PayrollEmploymentRecord {
    /**
     * Name of the employer as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'employerName': string;
    /**
     * Employer identification number (EIN)
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'legalEntityId'?: string;
    /**
     * The original hired date of an employee at the company
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'originalHireDate'?: number;
    /**
     * If an employee leaves the company and returns later, then the employer states the latest hire date at the company
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'latestHireDate'?: number;
    /**
     * The most recent pay period’s end date.
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'latestPayPeriodEndDate'?: number;
    /**
     * The most recent pay date from an employer
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'latestPayDate'?: number;
    /**
     * The number of days since an employee was last paid
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'daysSinceLastPay'?: number;
    /**
     * The number of pay cadences an employee has not been paid; determined by the pay frequency
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'numberPayCadenceWithoutPay'?: number;
    /**
     * The date an employee ended their employment at the company
     * @type {number}
     * @memberof PayrollEmploymentRecord
     */
    'employmentEndDate'?: number;
    /**
     * The length of time an employee has been employed with that employer in ISO 8601 format (e.g. P1Y6M0D)
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'employmentDuration'?: string;
    /**
     * Array of addresses
     * @type {Array<PayrollEmployerAddress>}
     * @memberof PayrollEmploymentRecord
     */
    'employerAddress'?: Array<PayrollEmployerAddress>;
    /**
     * \'Status codes: `A` - Active, `NLE` - No Longer Employed, `L` - Leave, `O` - Other\', `I` - Inactive, `U` - Unknown\'
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'employmentStatusCode': string;
    /**
     * \'Status name: `Active`, `No Longer Employed`, `Leave` or `Other`, `Inactive`, or `Unknown`\'
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'employmentStatusName': string;
    /**
     * Describes the employment status - it will be true if it is not directly stated by the employer, and false otherwise
     * @type {boolean}
     * @memberof PayrollEmploymentRecord
     */
    'derivedEmploymentStatus'?: boolean;
    /**
     * The abbreviate code for the employment level names (workLevelName) that we receive from the employer
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'workLevelCode'?: string;
    /**
     * The employment level name is whatever we receive from the employer, such as full time, part time, temp, contractor, and more
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'workLevelName'?: string;
    /**
     * The categorized work level status. Enumerations are:  * `Temporary`  * `Seasonal`  * `Retired`  * `Student`  * `Full Time`  * `Part Time`  * `Unspecified`  This is a new field, currently enabled only for testing reports. It will be added for all reports in August 2021. 
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'workLevelStatus': string;
    /**
     * Employee job title
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'positionTitle'?: string;
    /**
     * The length of time an employee has been employed at their current or latest position for this employment in ISO 8601 format (eg P1Y6M0D)
     * @type {string}
     * @memberof PayrollEmploymentRecord
     */
    'positionDuration'?: string;
}

