/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollEmployeeRecord } from './payroll-employee-record';
import { PayrollEmploymentRecord } from './payroll-employment-record';
import { PayrollVOIEIncomeRecord } from './payroll-voieincome-record';

/**
 * 
 * @export
 * @interface PayrollEmploymentHistoryVOIE
 */
export interface PayrollEmploymentHistoryVOIE {
    /**
     * The last time the payroll data was updated in the payroll provider\'s system
     * @type {number}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'asOfDate': number;
    /**
     * This is a Mastercard assigned ID to the employment record. It remains consistent for that employment record, even if the report is refreshed. It can be used to limit the employment records that are returned in the report.
     * @type {string}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'employmentId'?: string;
    /**
     * Name of the employer as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'employerName': string;
    /**
     * The name of the payroll source where the data was retrieved
     * @type {string}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'payrollSource': string;
    /**
     * 
     * @type {PayrollEmployeeRecord}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'employee': PayrollEmployeeRecord;
    /**
     * 
     * @type {PayrollEmploymentRecord}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'employment': PayrollEmploymentRecord;
    /**
     * 
     * @type {PayrollVOIEIncomeRecord}
     * @memberof PayrollEmploymentHistoryVOIE
     */
    'income': PayrollVOIEIncomeRecord;
}

