/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayrollEmployerAddress
 */
export interface PayrollEmployerAddress {
    /**
     * Employer address as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmployerAddress
     */
    'address1'?: string;
    /**
     * Employer city as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmployerAddress
     */
    'city'?: string;
    /**
     * Employer state as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmployerAddress
     */
    'state'?: string;
    /**
     * Employer zip code as stated by the employer in the payroll system
     * @type {string}
     * @memberof PayrollEmployerAddress
     */
    'zip'?: string;
}

