/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollReportConstraintsOut } from './payroll-report-constraints-out';

/**
 * 
 * @export
 * @interface PayrollReportAckAllOf
 */
export interface PayrollReportAckAllOf {
    /**
     * A report style. Possible values are directAPIPayroll, credentialedPayroll, paystatement, voieWithInterview, voieWithStatement, voieWithReport
     * @type {string}
     * @memberof PayrollReportAckAllOf
     */
    'reportStyle'?: string;
    /**
     * 
     * @type {PayrollReportConstraintsOut}
     * @memberof PayrollReportAckAllOf
     */
    'constraints'?: PayrollReportConstraintsOut;
}

