/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayrollDataOut
 */
export interface PayrollDataOut {
    /**
     * An ID to identify the data retrieved from the payroll providers for the report.
     * @type {string}
     * @memberof PayrollDataOut
     */
    'payrollDataRetrievalId'?: string;
    /**
     * An array of employmentIds
     * @type {Array<string>}
     * @memberof PayrollDataOut
     */
    'employmentIds'?: Array<string>;
    /**
     * An array of payrollAccountIds
     * @type {Array<string>}
     * @memberof PayrollDataOut
     */
    'payrollAccountIds'?: Array<string>;
    /**
     * A report ID
     * @type {string}
     * @memberof PayrollDataOut
     */
    'reportId'?: string;
}

