/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PortfolioReport } from './portfolio-report';

/**
 * 
 * @export
 * @interface PortfolioSummary
 */
export interface PortfolioSummary {
    /**
     * A unique identifier that will be consistent across all reports created for the same customer
     * @type {string}
     * @memberof PortfolioSummary
     */
    'portfolioId': string;
    /**
     * A list of reports in the portfolio
     * @type {Array<PortfolioReport>}
     * @memberof PortfolioSummary
     */
    'reports': Array<PortfolioReport>;
}

