/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PortfolioConsumer } from './portfolio-consumer';
import { PortfolioReport } from './portfolio-report';
import { PortfolioSummary } from './portfolio-summary';
import { PortfolioWithConsumerSummaryAllOf } from './portfolio-with-consumer-summary-all-of';

/**
 * @type PortfolioWithConsumerSummary
 * @export
 */
export type PortfolioWithConsumerSummary = PortfolioSummary & PortfolioWithConsumerSummaryAllOf;


