/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PrequalificationReportAssetSummary
 */
export interface PrequalificationReportAssetSummary {
    /**
     * The asset type: \"checking\", \"savings\", \"moneyMarket\", \"cd\", \"investment\"
     * @type {string}
     * @memberof PrequalificationReportAssetSummary
     */
    'type'?: string;
    /**
     * The available balance for the account
     * @type {number}
     * @memberof PrequalificationReportAssetSummary
     */
    'availableBalance'?: number;
    /**
     * The current balance of the account
     * @type {number}
     * @memberof PrequalificationReportAssetSummary
     */
    'currentBalance': number;
    /**
     * The two month average daily balance of the account
     * @type {number}
     * @memberof PrequalificationReportAssetSummary
     */
    'twoMonthAverage': number;
    /**
     * The six month average daily balance of the account
     * @type {number}
     * @memberof PrequalificationReportAssetSummary
     */
    'sixMonthAverage'?: number;
    /**
     * The beginning balance of the account per the time period of the report
     * @type {number}
     * @memberof PrequalificationReportAssetSummary
     */
    'beginningBalance': number;
}

