/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Receiver
 */
export interface Receiver {
    /**
     * Routing number of receiving bank
     * @type {string}
     * @memberof Receiver
     */
    'routingNumber': string;
    /**
     * Micro entries receiving account number of bank
     * @type {string}
     * @memberof Receiver
     */
    'accountNumber': string;
    /**
     * The list of supported account types. * \"checking\": Standard checking * \"savings\": Standard savings
     * @type {string}
     * @memberof Receiver
     */
    'accountType': string;
    /**
     * Name of the customer
     * @type {string}
     * @memberof Receiver
     */
    'name': string;
    /**
     * Transaction memo to be displayed for transactions
     * @type {string}
     * @memberof Receiver
     */
    'memo'?: string;
}

