/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportTransactionBase1 } from './report-transaction-base1';
import { ReportTransactionBase2 } from './report-transaction-base2';
import { ReportTransactionNewTxBasedAllOf } from './report-transaction-new-tx-based-all-of';

/**
 * @type ReportTransactionNewTxBased
 * @export
 */
export type ReportTransactionNewTxBased = ReportTransactionBase1 & ReportTransactionBase2 & ReportTransactionNewTxBasedAllOf;


