/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportIncomeEstimate
 */
export interface ReportIncomeEstimate {
    /**
     * Sum of all values in `netMonthlyIncome` over the previous 12 months
     * @type {number}
     * @memberof ReportIncomeEstimate
     */
    'netAnnual': number;
    /**
     * Projected net income over the next 12 months, across all income streams, based on `netAnnualIncome`
     * @type {number}
     * @memberof ReportIncomeEstimate
     */
    'projectedNetAnnual': number;
    /**
     * Before-tax gross annual income (estimated from `netAnnual`) across all income stream in the past 12 months
     * @type {number}
     * @memberof ReportIncomeEstimate
     */
    'estimatedGrossAnnual': number;
    /**
     * Projected gross income over the next 12 months, across all active income streams, based on `projectedNetAnnual`
     * @type {number}
     * @memberof ReportIncomeEstimate
     */
    'projectedGrossAnnual': number;
}

