/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StatePeriod } from './state-period';

/**
 * For a StateAttribute, describes a time interval type being reported and a list of periods generated according to that type.
 * @export
 * @interface StateTimeInterval
 */
export interface StateTimeInterval {
    /**
     * Periods of the specified time interval type, describing the attribute calculations
     * @type {Array<StatePeriod>}
     * @memberof StateTimeInterval
     */
    'periods': Array<StatePeriod>;
    /**
     * Possible values for strategies in which attributes may be aggregated and reported across varying time intervals. Allowed Values - MONTHLY_CALENDAR - MONTHLY_ROLLING_30
     * @type {string}
     * @memberof StateTimeInterval
     */
    'timeIntervalType': string;
}

