/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Describes a history of repeated transactions between the same parties.
 * @export
 * @interface StreamModel
 */
export interface StreamModel {
    /**
     * Number of days that occur between each transaction in the stream
     * @type {number}
     * @memberof StreamModel
     */
    'cadence': number;
    /**
     * Stream Id assigned to identified Stream
     * @type {string}
     * @memberof StreamModel
     */
    'id': string;
    /**
     * The party in the transaction that is receiving the funds
     * @type {string}
     * @memberof StreamModel
     */
    'payee': string;
    /**
     * The party in the transaction that is sending the funds
     * @type {string}
     * @memberof StreamModel
     */
    'payor': string;
    /**
     * Number of days since the last transaction occurred in the stream
     * @type {number}
     * @memberof StreamModel
     */
    'recency': number;
    /**
     * List of Transaction IDs that comprise the stream
     * @type {Array<string>}
     * @memberof StreamModel
     */
    'transactionIds': Array<string>;
}

