/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A fake transaction for TxPush testing
 * @export
 * @interface TestTxPushTransaction
 */
export interface TestTxPushTransaction {
    /**
     * The description of the transaction
     * @type {string}
     * @memberof TestTxPushTransaction
     */
    'description': string;
    /**
     * The amount of the transaction
     * @type {number}
     * @memberof TestTxPushTransaction
     */
    'amount': number;
    /**
     * \"active\" or \"pending\" (optional)
     * @type {string}
     * @memberof TestTxPushTransaction
     */
    'status'?: string;
    /**
     * A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof TestTxPushTransaction
     */
    'postedDate'?: number;
    /**
     * A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof TestTxPushTransaction
     */
    'transactionDate': number;
}

