/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThirdPartyAccessProduct } from './third-party-access-product';
import { ThirdPartyAccessProvenance } from './third-party-access-provenance';

/**
 * An object representing the third party access key request  * `customerId`: This is recipient\'s customer identifier * `partnerId`: This is recipient partner identifier * `thirdPartyPartnerId`: This is requester\'s partner identifier * `products`: Array of values representing the Mastercard Open Banking APIs for which access needs to be generated.
 * @export
 * @interface ThirdPartyAccessKeyData
 */
export interface ThirdPartyAccessKeyData {
    /**
     * A customer ID. See Add Customer API for how to create a customer ID.
     * @type {string}
     * @memberof ThirdPartyAccessKeyData
     */
    'customerId': string;
    /**
     * Your Partner ID displayed in the [Developer Dashboard](https://developer.mastercard.com/account/log-in)
     * @type {string}
     * @memberof ThirdPartyAccessKeyData
     */
    'partnerId': string;
    /**
     * Your Partner ID displayed in the [Developer Dashboard](https://developer.mastercard.com/account/log-in)
     * @type {string}
     * @memberof ThirdPartyAccessKeyData
     */
    'thirdPartyPartnerId': string;
    /**
     * 
     * @type {ThirdPartyAccessProvenance}
     * @memberof ThirdPartyAccessKeyData
     */
    'provenance'?: ThirdPartyAccessProvenance;
    /**
     * 
     * @type {Array<ThirdPartyAccessProduct>}
     * @memberof ThirdPartyAccessKeyData
     */
    'products': Array<ThirdPartyAccessProduct>;
}

