/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An object representing a digital signature of the access key
 * @export
 * @interface ThirdPartyAccessProof
 */
export interface ThirdPartyAccessProof {
    /**
     * The digital signature for the \"receipt\" portion of the access key
     * @type {string}
     * @memberof ThirdPartyAccessProof
     */
    'signature'?: string;
    /**
     * The Finicity key identifier is used to sign the access key
     * @type {string}
     * @memberof ThirdPartyAccessProof
     */
    'keyId'?: string;
    /**
     * A date-time with time zone
     * @type {string}
     * @memberof ThirdPartyAccessProof
     */
    'timestamp'?: string;
}

