/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Provenance regarding the calling client like `clientFingerprint`, `ipAddress` and `token`.
 * @export
 * @interface ThirdPartyAccessProvenance
 */
export interface ThirdPartyAccessProvenance {
    /**
     * Calling client identifier
     * @type {string}
     * @memberof ThirdPartyAccessProvenance
     */
    'clientFingerprint'?: string;
    /**
     * Calling client IP address
     * @type {string}
     * @memberof ThirdPartyAccessProvenance
     */
    'ipAddress'?: string;
    /**
     * Calling client cookie
     * @type {string}
     * @memberof ThirdPartyAccessProvenance
     */
    'token'?: string;
}

