/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThirdPartyAccessProof } from './third-party-access-proof';
import { ThirdPartyAccessReceipt } from './third-party-access-receipt';

/**
 * An object representing consent access data
 * @export
 * @interface ThirdPartyAccessReceiptData
 */
export interface ThirdPartyAccessReceiptData {
    /**
     * 
     * @type {ThirdPartyAccessReceipt}
     * @memberof ThirdPartyAccessReceiptData
     */
    'receipt'?: ThirdPartyAccessReceipt;
    /**
     * 
     * @type {ThirdPartyAccessProof}
     * @memberof ThirdPartyAccessReceiptData
     */
    'proof'?: ThirdPartyAccessProof;
}

