/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Transaction } from './transaction';

/**
 * A list of transactions
 * @export
 * @interface Transactions
 */
export interface Transactions {
    /**
     * The total number of results matching search criteria
     * @type {number}
     * @memberof Transactions
     */
    'found': number;
    /**
     * The number of results returned
     * @type {number}
     * @memberof Transactions
     */
    'displaying': number;
    /**
     * If the value of `moreAvailable` is \"true\", you can retrieve the next page of results by increasing the value of the start parameter in your next request:\"...&start=6&limit=5\"
     * @type {boolean}
     * @memberof Transactions
     */
    'moreAvailable': boolean;
    /**
     * Value of the `fromDate` request parameter that generated this response
     * @type {number}
     * @memberof Transactions
     */
    'fromDate': number;
    /**
     * Value of the `toDate` request parameter that generated this response
     * @type {number}
     * @memberof Transactions
     */
    'toDate': number;
    /**
     * Value of the sort request parameter that generated this response
     * @type {string}
     * @memberof Transactions
     */
    'sort': string;
    /**
     * The array of transactions
     * @type {Array<Transaction>}
     * @memberof Transactions
     */
    'transactions': Array<Transaction>;
}

