/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TxVerifyInterview
 */
export interface TxVerifyInterview {
    /**
     * An asset ID. Generated by Connect or by using the Store Customer Pay Statement API.
     * @type {string}
     * @memberof TxVerifyInterview
     */
    'assetId': string;
    /**
     * An array of account IDs to be included in the report (all accounts will be included if not set)
     * @type {Array<string>}
     * @memberof TxVerifyInterview
     */
    'accounts'?: Array<string>;
}

