/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VerifiedMicroDeposit
 */
export interface VerifiedMicroDeposit {
    /**
     * Micro entries successful verification status
     * @type {string}
     * @memberof VerifiedMicroDeposit
     */
    'status'?: string;
    /**
     * Micro entries successful verification description
     * @type {string}
     * @memberof VerifiedMicroDeposit
     */
    'statusDescription'?: string;
}

