/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountDetailsTxBased } from './account-details-tx-based';
import { PrequalificationReportAssetSummary } from './prequalification-report-asset-summary';
import { ReportAccountPosition } from './report-account-position';
import { ReportTransactionNewTxBased } from './report-transaction-new-tx-based';

/**
 * 
 * @export
 * @interface VOAReportAccount
 */
export interface VOAReportAccount {
    /**
     * The ID of the account
     * @type {number}
     * @memberof VOAReportAccount
     */
    'id'?: number;
    /**
     * The account number from the institution (all digits except the last four are obfuscated)
     * @type {string}
     * @memberof VOAReportAccount
     */
    'number'?: string;
    /**
     * The name(s) of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.
     * @type {string}
     * @memberof VOAReportAccount
     */
    'ownerName'?: string;
    /**
     * The mailing address of the account owner(s). This field is optional. If no owner information is available, this field will not appear in the report.
     * @type {string}
     * @memberof VOAReportAccount
     */
    'ownerAddress'?: string;
    /**
     * The account name from the institution
     * @type {string}
     * @memberof VOAReportAccount
     */
    'name'?: string;
    /**
     * One of the values from account types
     * @type {string}
     * @memberof VOAReportAccount
     */
    'type'?: string;
    /**
     * The available balance for the account
     * @type {number}
     * @memberof VOAReportAccount
     */
    'availableBalance'?: number;
    /**
     * The status of the most recent aggregation attempt
     * @type {number}
     * @memberof VOAReportAccount
     */
    'aggregationStatusCode'?: number;
    /**
     * The cleared balance of the account as-of balanceDate
     * @type {number}
     * @memberof VOAReportAccount
     */
    'balance'?: number;
    /**
     * A timestamp showing when the balance was captured
     * @type {number}
     * @memberof VOAReportAccount
     */
    'balanceDate'?: number;
    /**
     * The average monthly balance of this account
     * @type {number}
     * @memberof VOAReportAccount
     */
    'averageMonthlyBalance'?: number;
    /**
     * The count for the total number of insufficient funds transactions, based on the `fromDate` of the report.
     * @type {number}
     * @memberof VOAReportAccount
     */
    'totNumberInsufficientFundsFeeDebitTxAccount'?: number;
    /**
     * The count for the total number of insufficient funds transactions for the last two months, based on the `fromDate` of the report.
     * @type {number}
     * @memberof VOAReportAccount
     */
    'totNumberInsufficientFundsFeeDebitTxOver2MonthsAccount'?: number;
    /**
     * The number of days since the most recent insufficient funds transaction, based on the `fromDate` of the report.
     * @type {number}
     * @memberof VOAReportAccount
     */
    'totNumberDaysSinceMostRecentInsufficientFundsFeeDebitTxAccount'?: number;
    /**
     * a list of transaction records
     * @type {Array<ReportTransactionNewTxBased>}
     * @memberof VOAReportAccount
     */
    'transactions'?: Array<ReportTransactionNewTxBased>;
    /**
     * 
     * @type {AccountDetailsTxBased}
     * @memberof VOAReportAccount
     */
    'details'?: AccountDetailsTxBased;
    /**
     * 
     * @type {ReportAccountPosition}
     * @memberof VOAReportAccount
     */
    'position'?: ReportAccountPosition;
    /**
     * 
     * @type {PrequalificationReportAssetSummary}
     * @memberof VOAReportAccount
     */
    'asset'?: PrequalificationReportAssetSummary;
}

