/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VOIEPaystubPayStatement } from './voiepaystub-pay-statement';

/**
 * 
 * @export
 * @interface VOIEPaystubReportAllOf
 */
export interface VOIEPaystubReportAllOf {
    /**
     * The pay statements included in the report
     * @type {Array<string>}
     * @memberof VOIEPaystubReportAllOf
     */
    'assetIds'?: Array<string>;
    /**
     * Total number of billable pay statements included in the report
     * @type {number}
     * @memberof VOIEPaystubReportAllOf
     */
    'numberOfBillableAssets'?: number;
    /**
     * Extracted pay statement details, and the transaction matching summary
     * @type {Array<VOIEPaystubPayStatement>}
     * @memberof VOIEPaystubReportAllOf
     */
    'payStatements'?: Array<VOIEPaystubPayStatement>;
}

