/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BaseReportAckWithPortfolioId } from './base-report-ack-with-portfolio-id';
import { ErrorMessage } from './error-message';
import { PayrollEmploymentHistoryVOIE } from './payroll-employment-history-voie';
import { VOIEPayrollReportAllOf } from './voiepayroll-report-all-of';

/**
 * @type VOIEPayrollReport
 * A VOIE Payroll report
 * @export
 */
export type VOIEPayrollReport = BaseReportAckWithPortfolioId & VOIEPayrollReportAllOf;


