/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DirectDeposit } from './direct-deposit';
import { Employee } from './employee';
import { Employer } from './employer';
import { PayStat } from './pay-stat';
import { PayStatementForVoie } from './pay-statement-for-voie';
import { PaystubMonthlyIncomeRecord } from './paystub-monthly-income-record';
import { VOIEPaystubPayStatementAllOf } from './voiepaystub-pay-statement-all-of';

/**
 * @type VOIEPaystubPayStatement
 * @export
 */
export type VOIEPaystubPayStatement = PayStatementForVoie & VOIEPaystubPayStatementAllOf;


