/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollEmploymentHistoryVOIE } from './payroll-employment-history-voie';

/**
 * 
 * @export
 * @interface VOIEPayrollReportAllOf
 */
export interface VOIEPayrollReportAllOf {
    /**
     * An array of employment histories, one for each of the consumer\'s verified employers
     * @type {Array<PayrollEmploymentHistoryVOIE>}
     * @memberof VOIEPayrollReportAllOf
     */
    'employmentHistory'?: Array<PayrollEmploymentHistoryVOIE>;
    /**
     * Mastercard Open Banking internal use only to flag reports that should not be retrieved by the GSE\'s (Government-Sponsored Enterprise).  This is a mandatory field for VOE-payroll and VOIE-payroll report types.
     * @type {boolean}
     * @memberof VOIEPayrollReportAllOf
     */
    'gseEnabled'?: boolean;
    /**
     * A report style. Possible values are directAPIPayroll, credentialedPayroll, paystatement, voieWithInterview, voieWithStatement, voieWithReport
     * @type {string}
     * @memberof VOIEPayrollReportAllOf
     */
    'reportStyle'?: string;
}

