/*
Open Banking

OpenAPI specification for Finicity APIs.

Open Banking solutions in the US are provided by Finicity, a Mastercard
company.

The version of the OpenAPI document: 1.16.0
Contact: apisupport@mastercard.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportIncomeStreamSummary } from './report-income-stream-summary';
import { ReportInstitution } from './report-institution';

/**
 * 
 * @export
 * @interface VOIReportAllOf
 */
export interface VOIReportAllOf {
    /**
     * The `postedDate` of the earliest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof VOIReportAllOf
     */
    'startDate'?: number;
    /**
     * The `postedDate` of the latest transaction analyzed for the report. A date in Unix epoch time (in seconds). See: [Handling Epoch Dates and Times](https://developer.mastercard.com/open-banking-us/documentation/codes-and-formats/).
     * @type {number}
     * @memberof VOIReportAllOf
     */
    'endDate'?: number;
    /**
     * Number of days covered by the report
     * @type {number}
     * @memberof VOIReportAllOf
     */
    'days'?: number;
    /**
     * \"true\" if the report covers more than 180 days
     * @type {boolean}
     * @memberof VOIReportAllOf
     */
    'seasoned'?: boolean;
    /**
     * A list of institution records
     * @type {Array<ReportInstitution>}
     * @memberof VOIReportAllOf
     */
    'institutions'?: Array<ReportInstitution>;
    /**
     * Income details
     * @type {Array<ReportIncomeStreamSummary>}
     * @memberof VOIReportAllOf
     */
    'income'?: Array<ReportIncomeStreamSummary>;
}

